<?php

/**
 * @file
 * Implements payment features for Commerce Store.
 */

/**
 * Implements hook_menu().
 */
function commerce_store_payment_menu() {
  $items = array();

  $items['admin/commerce/stores/%commerce_store/payment_methods'] = array(
    'title' => 'Payment methods',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'commerce_store_payment_methods_overview',
    'page arguments' => array(3),
    'access callback' => 'commerce_store_access',
    'access arguments' => array('update', 3),
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_store_payment.admin.inc',
  );

  foreach (commerce_store_payment_enabled_methods() as $method_id => $payment_method) {
    $items['admin/commerce/stores/%commerce_store/payment_methods/' . $method_id] = array(
      'title' => $payment_method['title'],
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'commerce_store_payment_method_form_wrapper',
      'page arguments' => array(3, 5),
      'access callback' => 'commerce_store_access',
      'access arguments' => array('update', 3),
      'weight' => 0,
      'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
      'file' => 'includes/commerce_store_payment.admin.inc',
    );
  }

  return $items;
}

/**
 * Returns definitions of all payment methods enabled site-wide.
 */
function commerce_store_payment_enabled_methods() {
  // Get all payment method definitions.
  $payment_method_definitions = commerce_payment_methods();

  // Create a dummy order and invoke the payment methods event that will
  // populate it with an array of method IDs for available payment methods.
  $order = (object) array('payment_methods' => array());
  rules_invoke_all('commerce_payment_methods', $order);

  // Return only enabled payment method definitions.
  $enabled_payment_methods = array();
  foreach ($order->payment_methods as $payment_method) {
    $method_id = $payment_method['method_id'];
    $enabled_payment_methods[$method_id] = $payment_method_definitions[$method_id];
  }

  return $enabled_payment_methods;
}

/**
 * Implements hook_form_FORM_ID_alter() for commerce_store_ui_store_form().
 *
 * @see commerce_store_ui_store_form()
 */
function commerce_store_payment_form_commerce_store_ui_store_form_alter(&$form, &$form_state) {
  $store = $form_state['build_info']['args'][0];

  $form['payment_methods'] = array(
    '#type' => 'fieldset',
    '#access' => user_access('administer stores'),
    '#title' => t('Payment methods'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#attributes' => array(
      'class' => array('store-form-payment-methods'),
    ),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'commerce_store_payment') . '/commerce_store_payment.js',
      ),
    ),
    '#weight' => 30,
  );
  foreach (commerce_store_payment_enabled_methods() as $method_id => $payment_method) {
    $form['payment_methods']['enabled'][$method_id] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable %method payment method', array('%method' => $payment_method['title'])),
      '#tree' => TRUE,
      '#attributes' => array('title' => $payment_method['title']),
      '#default_value' => !empty($store->data['payment_methods']['enabled'][$method_id]),
    );
  }

  array_unshift($form['actions']['submit']['#submit'], 'commerce_store_payment_commerce_store_form_submit');
}

/**
 * Form submission handler for commerce_store_ui_store_form().
 *
 * @see commerce_store_payment_form_commerce_store_ui_store_form_alter()
 */
function commerce_store_payment_commerce_store_form_submit($form, &$form_state) {
  $store = &$form_state['build_info']['args'][0];

  $store->data['payment_methods']['enabled'] = $form_state['values']['payment_methods']['enabled'];
}

/**
 * Implements hook_query_TAG_alter().
 *
 * This actually is almost an exact copy of
 * commerce_payment_query_commerce_payment_transaction_access_alter(), needed
 * because we need to join with "commerce_store" table BEFORE calling
 * commerce_entity_access_query_alter() function.
 * For the same reason we needed to set commerce_store_payment module weight
 * to -1, so this hook_query_TAG_alter() implementation is called before that
 * one from commerce_payment module
 * (commerce_payment_query_commerce_payment_transaction_access_alter()).
 */
function commerce_store_payment_query_commerce_payment_transaction_access_alter(QueryAlterableInterface $query) {
  // Read the meta-data from the query.
  if (!$account = $query->getMetaData('account')) {
    global $user;
    $account = $user;
  }

  // If the user has the administration permission, nothing to do.
  if (user_access('administer payments', $account)) {
    return;
  }

  // Join the payment transaction to their orders.
  if (user_access('view payments', $account)) {
    $tables = &$query->getTables();

    // Look for an existing commerce_order table.
    foreach ($tables as $table) {
      if ($table['table'] === 'commerce_order') {
        $order_alias = $table['alias'];
        break;
      }
    }

    // If not found, attempt a join against the first table.
    if (!isset($order_alias)) {
      reset($tables);
      $base_table = key($tables);
      $query->innerJoin('commerce_order', 'commerce_order', '%alias.order_id = ' . $base_table . '.order_id');
    }

    // Make sure a join with commerce_store table is added to the query.
    commerce_store_entity_access_query_alter($query, 'commerce_order', 'commerce_order');
  }
  else {
    // The user has access to no payment transaction.
    $query->where('1 = 0');
  }
}
